Don't force HTTPS pages
At least on my system Flatpak is having SSL issues while pulling updates
from the repo (output with `env OSTREE_DEBUG_HTTP=1`):

```
Installing 1/2…
F: flatpak_dir_pull: Using commit f9b5e50fcf56e43d176ecd346f12894dea9d4cb10342fd859dcceda294727e58 for pull of ref runtime/org.mozilla.FirefoxNightly.Locale/x86_64/master from remote firefoxnightly1-origin
Installing 1/2…                        0%  0 bytes/s
*   Trying 35.185.44.232:443...
Installing 1/2…                        0%
* Connected to projects261.gitlab.io (35.185.44.232) port 443 (#0)
* SSL connection timeout
* Closing connection 0
Warning: While pulling runtime/org.mozilla.FirefoxNightly.Locale/x86_64/master from remote firefoxnightly1-origin: While fetching https://projects261.gitlab.io/firefox-nightly-flatpak/objects/f9/b5e50fcf56e43d176ecd346f12894dea9d4cb10342fd859dcceda294727e58.commitmeta: [28] Timeout was reached
Installing 2/2…
F: flatpak_dir_pull: Using commit 56899016bc6d69c3f81ce7f1fb4f062b50365faf4d189c750bf2fa1918851c14 for pull of ref app/org.mozilla.FirefoxNightly/x86_64/master from remote firefoxnightly1-origin
*   Trying 35.185.44.232:443...
* Connected to projects261.gitlab.io (35.185.44.232) port 443 (#0)
* SSL connection timeout
* Closing connection 0
Installing 2/2…                        0%  0 bytes/s
Error: While pulling app/org.mozilla.FirefoxNightly/x86_64/master from remote firefoxnightly1-origin: While fetching https://projects261.gitlab.io/firefox-nightly-flatpak/config: [28] Timeout was reached
error: Failed to install org.mozilla.FirefoxNightly: While pulling app/org.mozilla.FirefoxNightly/x86_64/master from remote firefoxnightly1-origin: While fetching https://projects261.gitlab.io/firefox-nightly-flatpak/config: [28] Timeout was reached
```
I can access both 35.185.44.232:443 and projects261.gitlab.io with curl,
openssl and my browser. So I'm not sure what specifically is causing
Flatpak to fail. Might be an issue on Gitlab.com's part.

In the meantime, don't force https in `Pages>Force HTTPS` and downgrade
the repo URL to HTTP. This seems to be the only combination that is
working.

This is probably a temporary change.

Meanwhile ostree verifies each file and the summary with GPG, they are
signed by my public key.